# File: .github/workflows/repo-sync.yml

on:
  schedule:
  - cron:  "*/1 * * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: https://github.com/dorelljames/gatsby-starter-blog/new/master
        source_branch: master
        destination_branch: original
        github_token: b8550db28bdabe47a059fe6276287f15e5f60270
